# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/google/steelhead/extract-files.sh - DO NOT EDIT

# All the blobs necessary for steelhead, derived from maguro
PRODUCT_COPY_FILES += \
    vendor/google/steelhead/proprietary/pvrsrvinit:system/vendor/bin/pvrsrvinit \
    vendor/google/steelhead/proprietary/bcm4330.hcd:system/vendor/firmware/bcm4330.hcd \
    vendor/google/steelhead/proprietary/ducati-m3.bin:system/vendor/firmware/ducati-m3.bin \
    vendor/google/steelhead/proprietary/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
    vendor/google/steelhead/proprietary/libEGL_POWERVR_SGX540_120.so:system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \
    vendor/google/steelhead/proprietary/libGLESv1_CM_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
    vendor/google/steelhead/proprietary/libGLESv2_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
    vendor/google/steelhead/proprietary/gralloc.omap4.so:system/vendor/lib/hw/gralloc.omap4.so \
    vendor/google/steelhead/proprietary/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/google/steelhead/proprietary/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/google/steelhead/proprietary/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/google/steelhead/proprietary/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/google/steelhead/proprietary/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
    vendor/google/steelhead/proprietary/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/google/steelhead/proprietary/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/google/steelhead/proprietary/libusc.so:system/vendor/lib/libusc.so

# Blobs unique to steelhead
PRODUCT_COPY_FILES += \
    vendor/google/steelhead/proprietary/sledadk_controller.bin:system/vendor/firmware/sledadk_controller.bin \
    vendor/google/steelhead/proprietary/smc_pa_wvdrm.ift:system/vendor/firmware/smc_pa_wvdrm.ift \
    vendor/google/steelhead/proprietary/smc_normal_world_android_cfg.ini:system/vendor/etc/smc_normal_world_android_cfg.ini \
    vendor/google/steelhead/proprietary/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/google/steelhead/proprietary/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/google/steelhead/proprietary/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/google/steelhead/proprietary/libwvm.so:system/vendor/lib/libwvm.so

